#!/bin/bash
#
# select the OS, and compile all libraries + driver

if [ `uname -s` = "Darwin" ];
then
  # Mac OS X
  cd Makefile-headers
  ./selectMacOSX
  echo "OS selection: Mac OS X."
  cd ..
else
  # Linux
  cd Makefile-headers
  ./selectLinux
  echo "OS selection: Linux."
  cd ..
fi

make

echo 'Note: Examples are in the "examples" subfolder. Binaries are in the "utilities/bin" subfolder.'

